# Generated by Django 3.2.9 on 2021-12-09 09:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='v1638348565/owuk4syvculcljuzdron.jpg', max_length=255, verbose_name='image'),
        ),
    ]
